### PR TITLE
Change from jellyfin-api-dart to openapi

### PR DESCRIPTION
**Pull request by Kara-Zor-El**
## Why?
 - Trying to shift Jellyfin dart clients to all use tentacle

### CODE REVIEW

**Review by jdk-21 — APPROVED** [review]
Thank you

**Comment by jdk-21** [comment]
I'm using Mainline for Jellyflix. So merging this would result in a new stable version. Could you add tentacle to the development branch first?

**Comment by Kara-Zor-El** [comment]
Hey,

Changed the branch. Anything else needed?

**Review by jdk-21 — APPROVED** [review]
Great work. Thank you.

**Pull request merged**
