### PR TITLE
Feature/scaling

### LINKED ISSUE #68: [Issue]: Posters do not scale with window size
### Please describe your bug

Wherever present, the posters should scale so that 6 - 7 posters are showing. This will also improve legibility.

### Jellyflix Version

Other

### if other:

development

### Jellyfin Version

10.8.13

### if other:

_No response_

### Environment

```markdown
- OS: Debian
- OS Version: Trixie
- Playback Method: NA
```

### LINKED ISSUE #70: [Issue]: Synopsis text is too small
Text for the description of items in details screens is too small.

### PR DESCRIPTION
**Pull request by sevenrats**
- Implement UI scaling using new JfxTile, JfxLayout, and JfxTextTheme components.  
- Fix "Show more" logic in details synopsis
- break the button row out (quite brutally, sorry) into its own widget so that detail view is not a mind prison

Things I seriously need help with from you, yes *you*:

- [x] This is not the right poster spacing. It needs some time spent on it to give the tiles the right amount of breathing room
- [x] probably related to above, in the detail view there is an unpleasant black matte to the right of  the featured poster.

Things that need to be done but I think should be separate pull requests:
- Implement library views that use JfxTile
- Use JfxTile for Search results
- Clean up the button bar further and make the other buttons scale with the play button. right now the secondary buttons still have static size and imho we should leave it in the interest of scope control.

fixes #68 
fixes #70

### CODE REVIEW

**Comment by sevenrats** [comment]
fixes #68 
fixes #70

**Comment by sevenrats** [comment]
oh actually i need to do something about the new deadspace at the top of smaller landscape views.

**Comment by sevenrats** [comment]
I've tested this on android and linux and I'm happy with it.  super grateful for you fixing those issues so quickly!
Anything beyond this should be additional PRs imho.

**Comment by sevenrats** [comment]
The new roadmap to this not being a draft:

- [ ] consider fine tuning the size of title and year
- [ ] address the newly introduced rending overlow in the banner

**Comment by sevenrats** [comment]
i dont have the bandwidth for the banner right now and I think its fine.

**Comment by jdk-21** [comment]
Thank you for your help.
I added the banner scaling and I added a minimum size for the item carousel.

**Pull request merged**
