### PR TITLE
Increase send timeout to 10 seconds

### LINKED ISSUE #49: [Issue]:  Playback fails
### Please describe your bug

Tested on both Ubuntu 22 and debian bookworm, chrome and firefox.  Playback never happens when using the demo server, trying several different titles.

### Jellyflix Version

0.9.13

### if other:

_No response_

### Jellyfin Version

10.8.13

### if other:

_No response_

### Environment

```markdown
- OS: debuntu stable
- OS Version: 22/bookworm respectively
- Playback Method: im not actually sure it didnt work, so.
```

### PR DESCRIPTION
**Pull request by sevenrats**
partially fixes #49 by uncommenting directplay block and fixing directplay url

### CODE REVIEW

**Comment by jdk-21** [comment]
Removing "Static" will break the Progressbar in the PlayerScreen. That's why I would like to only deactivate it for certain mediatype configurations. There is a great chance that we can still direct play it with static enabled. MPV can playback almost anything. Let's further discuss your issue in #49

**Comment by sevenrats** [comment]
including "Static" creates an invalid URL. This is the reason it was removed.  What exactly is it supposed to be doing?

**Comment by sevenrats** [comment]
lol this was just a dang timeout.

**Comment by sevenrats** [comment]
this isn't it either. something to do with my remote backend I think. either way I can't reproduce this outside of my environment.

**Pull request closed without merging**
