### PR TITLE
some rec header improvements

### PR DESCRIPTION
**Pull request by sevenrats**
1) We no longer scroll if the cursor is in the rec header, because that was annoying
2) We make a slightly different API request that is more in keeping with user expectation from a rec header, and is less redundant given that plenty of stuff similar to similarItemsByLastWatched exists on the page already. This change is important because having the header change every time we browse home is a) disorienting, since once a user has seen a banner there they may want to browse back to click it and b) not performant because it circumvents the cache.  just hitting the two api requests and loading the cached images is the correct approach because it will be as fast as possible while still loading server side changes. 
It would be nice to make a single API request instead of two but 10.9 is going to drop soon and this will allow us to use the more intuitive "most recent episode added" selector for series.
there is a small bug here where if there is only a series library or only a movie library, the banner list will be quite short. i dont think its a real issue though.

### CODE REVIEW

**Comment by jdk-21** [comment]
Sorry, I'm just only my phone right now, but this change looks great. We can further improve the API request by doing only one request and filtering for both Series, Movies and maybe Episodes at once. That way we may have only movies or series in the header, but I think that's ok. 
My initial idea of the header was the discovery of items, because the newest series and movies are already in the first three carousels. Maybe you could try random sort order instead of descending.

**Comment by sevenrats** [comment]
id like to follow up to this PR with another that removes much of this home screen logic.  both "recently added" rows will get removed in that PR, but my intention is to implement library views first.  we don't need to show the user 20 new titles imho.  they will get used to the rec header and when it changes, they will know its time to open a library, sort by date added and look for new stuff. 
i would probably reduce the homescreen to the rec header, continue watching, and the rec footer. in that form the home screen is super snappy. i will also attempt to add a row for individual library view a la web app.  genres and top ten absolutely must go, and much of the rest  could stay but it wants for UX optimization in my opinion.

**Comment by sevenrats** [comment]
this is the reason for the two requests, ultimately: https://github.com/jellyfin/jellyfin-web/pull/3970
because movies and series will wind up with different selection arguments soon. if the banner represents "stuff we are telling you about because we know you didnt know about it because its new," then it makes more sense to use episode added date for series.

**Comment by sevenrats** [comment]
if you aren't comfortable with changing the api calls right now I can put them back in this PR and we can just merge the hover functionality

**Comment by jdk-21** [comment]
> this is the reason for the two requests, ultimately: [jellyfin/jellyfin-web#3970](https://github.com/jellyfin/jellyfin-web/pull/3970) because movies and series will wind up with different selection arguments soon. if the banner represents "stuff we are telling you about because we know you didnt know about it because its new," then it makes more sense to use episode added date for series.

I didn't know that yet. Then it's totally fine.

**Comment by jdk-21** [comment]
After trying it, I think it would make more sense to only stop the carousel if you hover over the buttons, which indicates that you want to click them.

**Comment by sevenrats** [comment]
I did start out experimenting with smaller mouse regions, but it didn't feel as intuitive.  i wound up selecting the entire banner because you cant seelect only the interface column because it leaves the bottom buttons behind, and you can't select just the bottom buttom row because it leaves the playback buttons behind.  so the only way that got the playback buttonrow and the banner buttons at the bottom was the make the mouseregion the outer barrier.  we could do two mouseregions, probably, but honestly this feels pretty intuitive to me as is, like, holding the page of a book you are reading.

**Review by jdk-21 — APPROVED** [review]

**Pull request merged**
